name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - x86
        node:
          - 8
          - 10
          - 12
          - 14
          - 16
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          - arch: x86
            os: macOS-latest
          - arch: x86
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - run: npm install
      - run: npm run lint
        if:
          matrix.os == 'ubuntu-latest' && matrix.node == 16 && matrix.arch ==
          'x64'
      - run: npm test
